name: news_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  get_it: ^8.0.2
  http: ^1.2.2
  intl: ^0.20.0
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  sqflite: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.13
  floor_generator: ^1.5.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli Light.ttf
          weight: 300

    - family: Butler
      fonts:
        - asset: assets/fonts/muli/Butler.ttf
    - family: Horizon
      fonts:
        - asset: assets/fonts/Horizon.ttf
